name: QAPlayground

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:                  # Triggers the pipeline on a daily schedule
    - cron: '0 8 * * *'      # Runs daily at 8AM UTC

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: QAPlayground                        # Replace with your solution name, i.e. MyWpfApp.sln.
      Test_Project_Path: QAPlayground/QAPlayground.csproj                 # Replace with the path to your test project, i.e. MyWpfApp.Tests\MyWpfApp.Tests.csproj.
     
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test --logger "trx;LogFileName=TestResults/test_results_$(date +'%Y%m%d%H%M%S').trx"
      
    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: Test Results
        path: QAPlayground/TestResults
        
    - name: Upload Extent Reports
      uses: actions/upload-artifact@v3
      with:
        name: Test Results
        path: QAPlayground/QAPlayground/bin/Debug/net6.0/TestResults/ExtentReport*.html
